import { 
  Printer, Droplet, Monitor, Settings, Wrench, Mouse, Keyboard, Link, Zap, Wifi, HardDrive
} from 'lucide-react';

export const dummyProducts = [
  // --- PRINTERS (INKJET) ---
  { id: 'epson_l8050', name: 'Epson L8050', type: 'INKJET', price: 24199, brand: 'Epson', rating: 4.8, imageIcon: Printer, badge: 'Pro Photo', badgeColor: 'bg-purple-500', description: "A specialized 6-color wireless ink tank printer engineered primarily for high-resolution, borderless photographic output.", details: "Built with an integrated, space-saving tank architecture and features easily accessible maintenance components to reduce servicing delays.", specifications: [{label: 'Resolution', value: '5760 dpi max print resolution'}, {label: 'Connectivity', value: 'Wi-Fi Direct support'}, {label: 'Print Speed', value: 'Standard 4R photo in ~25 seconds'}], features: ['Borderless A4 printing', 'Direct-to-CD/DVD surface printing', 'PVC/ID card printing capability', 'Epson Smart Panel application integration'] },
  { id: 'canon_g2010', name: 'Canon G2010', type: 'INKJET', price: 14095, brand: 'Canon', rating: 4.5, imageIcon: Printer, badge: 'Bestseller', badgeColor: 'bg-green-500', description: "A robust, high-capacity refillable ink tank all-in-one printer engineered for continuous, heavy-duty document processing.", details: "Designed to maintain a minimal desk footprint while driving down running costs through its built-in tank infrastructure.", specifications: [{label: 'Resolution', value: '4800x1200 dpi'}, {label: 'Connectivity', value: 'High-speed USB'}, {label: 'Power', value: 'TEC of ~0.1 kWh'}], features: ['Integrated ink reservoirs', 'High page output yield', 'Dedicated Quiet Mode for office environments'] },
  { id: 'canon_g2012', name: 'Canon G2012', type: 'INKJET', price: 15275, brand: 'Canon', rating: 4.6, imageIcon: Printer, badge: null, badgeColor: '', description: "An economical, multi-functional ink tank system focused on high-volume printing tasks with minimal ink wastage.", details: "Acts as the natural successor in the G2000 series, heavily optimizing multi-page document handling.", specifications: [{label: 'Resolution', value: '4800x1200 dpi'}, {label: 'Connectivity', value: 'Standard USB'}, {label: 'Functions', value: 'Print, Copy, Scan'}], features: ['Comprehensive Print, Copy, and Scan functions', 'Borderless image printing', 'Economical ink usage'] },
  { id: 'canon_g3010', name: 'Canon G3010', type: 'INKJET', price: 13699, brand: 'Canon', rating: 4.7, imageIcon: Printer, badge: 'Wireless Pick', badgeColor: 'bg-blue-500', description: "A wireless-enabled, all-in-one ink tank printer that brings network accessibility to high-yield document generation.", details: "Features built-in Wi-Fi, permitting users to print from various localized nodes without the need for physical wired connections.", specifications: [{label: 'Resolution', value: '4800x1200 dpi'}, {label: 'Connectivity', value: 'Wi-Fi, USB 2.0 interface'}], features: ['Cloud link support', 'Direct mobile device printing', 'Utilizes high-density pigment black ink for sharp text'] },
  { id: 'canon_g3012', name: 'Canon G3012', type: 'INKJET', price: 18775, brand: 'Canon', rating: 4.6, imageIcon: Printer, badge: null, badgeColor: '', description: "An advanced multi-function wireless unit optimized to deliver highly stable network performance for business use.", details: "Strategically designed to lower the Total Cost of Ownership (TCO) across a standard three-year enterprise deployment.", specifications: [{label: 'Resolution', value: '4800x1200 dpi'}, {label: 'Connectivity', value: 'Integrated Wi-Fi and LAN protocols'}], features: ['Broad compatibility with Auto Document Feeders', 'Deep integration with mobile printing applications', 'Stable network performance'] },
  { id: 'canon_g4010', name: 'Canon G4010', type: 'INKJET', price: 21661, brand: 'Canon', rating: 4.5, imageIcon: Printer, badge: 'Office Ready', badgeColor: 'bg-orange-500', description: "A complete 4-in-1 wireless ink tank solution that integrates traditional faxing and automated document feeding.", details: "Ideal for small offices that require legacy telecommunication fax capabilities alongside modern wireless networking.", specifications: [{label: 'Connectivity', value: 'Wi-Fi, USB'}, {label: 'Hardware', value: 'Equipped with an Auto Document Feeder (ADF)'}], features: ['Seamless Print, Copy, Scan, and Fax capabilities', 'Borderless photo output', 'Ships with high-volume ink'] },
  { id: 'canon_g2770', name: 'Canon G2770', type: 'INKJET', price: 11209, brand: 'Canon', rating: 4.8, imageIcon: Printer, badge: null, badgeColor: '', description: "A modernized multi-function ink tank printer that introduces an enhanced onboard user interface.", details: "Incorporates a 1.2-inch LCD screen, allowing users to operate the device and check statuses without needing a host computer.", specifications: [{label: 'Print Speeds', value: '11 ppm (Monochrome) / 6 ppm (Color)'}, {label: 'Resolution', value: '4800x1200 dpi'}], features: ['Easy-to-fill ink tanks', 'Integrated LCD display', 'Rapid monochrome document output'] },
  { id: 'canon_g3770', name: 'Canon G3770', type: 'INKJET', price: 15177, brand: 'Canon', rating: 4.9, imageIcon: Printer, badge: 'New Arrival', badgeColor: 'bg-blue-500', description: "A versatile wireless multi-function ink tank printer equipped with advanced network routing and a clear display panel.", details: "Perfectly bridges the gap between home-office simplicity and the complex networking needs of small corporate groups.", specifications: [{label: 'Connectivity', value: 'Ethernet port, USB, Wi-Fi Direct, Wireless networking'}], features: ['1.35-inch LCD navigation panel', 'Supports Automatic 2-Sided (Duplex) printing', 'Advanced network routing'] },
  { id: 'canon_g570', name: 'Canon G570', type: 'INKJET', price: 17949, brand: 'Canon', rating: 4.7, imageIcon: Printer, badge: null, badgeColor: '', description: "A dedicated, single-function 6-color photo ink tank printer aimed at imaging enthusiasts.", details: "Leverages unique red and grey inks to dramatically widen the reproducible color spectrum for professional-grade photography.", specifications: [{label: 'Output', value: 'Specialized high-resolution photo output'}, {label: 'Connectivity', value: 'Dual USB/Wi-Fi interfaces'}], features: ['6-color dye system', 'User-replaceable maintenance cartridge', 'Modular print head design'] },
  { id: 'canon_g670', name: 'Canon G670', type: 'INKJET', price: 17949, brand: 'Canon', rating: 4.9, imageIcon: Printer, badge: 'Pro Photo', badgeColor: 'bg-purple-500', description: "A premium, multi-functional 6-color photo ink tank system combining top-tier imaging with scanning capabilities.", details: "Takes the high-fidelity photographic engine of the G570 and wraps it in a chassis with full copying and scanning infrastructure.", specifications: [{label: 'Resolution', value: '4800x1200 dpi'}, {label: 'Print Speed', value: '3.9 images per minute'}, {label: 'Compatibility', value: 'Windows and Chrome OS'}], features: ['Wireless connectivity', 'True borderless output', 'High-yield 6-color ink reservoirs', 'User-serviceable maintenance box'] },
  { id: 'hp_525', name: 'HP Smart Tank 525', type: 'INKJET', price: 10999, brand: 'HP', rating: 4.5, imageIcon: Printer, badge: null, badgeColor: '', description: "A robust entry-level all-in-one color ink tank printer from Hewlett-Packard.", details: "Ships with a massive initial ink supply designed to eliminate the need for replacement consumables for an extended period.", specifications: [{label: 'Connectivity', value: 'Standard USB interface'}, {label: 'Functions', value: 'Comprehensive Print/Copy/Scan capability'}], features: ['Simplified guided setup process', 'Includes ink sufficient for up to 12,000 black pages', 'Includes ink sufficient for up to 8,000 color pages'] },
  { id: 'hp_580', name: 'HP Smart Tank 580', type: 'INKJET', price: 15447, brand: 'HP', rating: 4.6, imageIcon: Printer, badge: null, badgeColor: '', description: "A wireless all-in-one ink tank printer outfitted with self-healing connectivity protocols.", details: "Engineered specifically for environments suffering from unstable internet, featuring resilient wireless networking hardware.", specifications: [{label: 'Connectivity', value: 'Wi-Fi capability, USB interface'}], features: ['Bundles high-capacity ink', 'Borderless photo printing', 'Mobile Fax capabilities via HP Smart App', 'Intelligent self-healing Wi-Fi system'] },
  { id: 'hp_585', name: 'HP Smart Tank 585', type: 'INKJET', price: 13927, brand: 'HP', rating: 4.7, imageIcon: Printer, badge: null, badgeColor: '', description: "A premium variation of the 580 series, bringing slight aesthetic changes and specific retail bundling.", details: "Delivers identical high-tier performance to the 580, optimized primarily for distinct regional retail channels.", specifications: [{label: 'Connectivity', value: 'Wi-Fi, USB'}, {label: 'Functions', value: 'Print, Copy, Scan'}], features: ['Spill-free ink replenishment system', 'Full integration with the HP Smart application'] },
  
  // --- PRINTERS (LASER) ---
  { id: 'hp_303d', name: 'HP Laser 303d', type: 'LASER', price: 28000, brand: 'HP', rating: 4.5, imageIcon: Printer, badge: null, badgeColor: '', description: "A high-velocity, single-function monochrome laser printer tailored for heavy enterprise use.", details: "Constructed to power through demanding corporate print queues without suffering from thermal throttling or memory delays.", specifications: [{label: 'Print Speeds', value: 'Up to 30 ppm (A4 size)'}, {label: 'Hardware', value: 'Automatic Duplexing'}], features: ['Standard two-sided printing', 'Relies on unmatched durability of Original HP Toner', 'Includes a guided setup'] },
  { id: 'hp_303dw', name: 'HP Laser 303dw', type: 'LASER', price: 28000, brand: 'HP', rating: 4.8, imageIcon: Printer, badge: 'Wireless Pick', badgeColor: 'bg-blue-500', description: "A rapid, single-function monochrome laser printer integrating complex wireless connectivity.", details: "Blends modern wireless and network protocols with a highly durable 30 ppm enterprise print engine.", specifications: [{label: 'Print Speeds', value: 'Up to 30 ppm (A4)'}, {label: 'Connectivity', value: 'Integrated Wi-Fi'}, {label: 'Hardware', value: 'Automatic Duplex support'}], features: ['Utilizes Original HP Toner', 'Supports Wi-Fi Direct', 'Offers corporate network routing capabilities'] },
  { id: 'hp_323d', name: 'HP Laser MFP 323d', type: 'LASER', price: 22499, brand: 'HP', rating: 4.6, imageIcon: Monitor, badge: null, badgeColor: '', description: "A multi-functional A4 monochrome laser printer built for robust document processing.", details: "Melds high-speed document copying and scanning into the proven 300-series laser architecture.", specifications: [{label: 'Output Speed', value: '30 ppm'}, {label: 'Connectivity', value: 'Standard USB connection'}, {label: 'Hardware', value: 'Built-in Automatic Duplexing'}], features: ['Complete Print, Copy, and Scan functionality', 'Automated two-sided printing'] },
  { id: 'hp_323dnw', name: 'HP Laser MFP 323dnw', type: 'LASER', price: 19999, brand: 'HP', rating: 4.9, imageIcon: Monitor, badge: null, badgeColor: '', description: "A network-optimized multi-function monochrome laser printer tailored for decentralized offices.", details: "Enhances the 323 base chassis with advanced networking protocols to allow for seamless mobile and multi-user access.", specifications: [{label: 'Output Speed', value: '30 ppm'}, {label: 'Connectivity', value: 'Ethernet port, Wi-Fi, USB interface'}], features: ['Supports Mopria and Apple AirPrint', 'Automatic duplexing', 'Advanced network routing'] },
  { id: 'hp_laser_323sdnw', name: 'HP Laser MFP 323sdnw', type: 'LASER', price: 25499, brand: 'HP', rating: 4.9, imageIcon: Monitor, badge: 'Flagship Deal', badgeColor: 'bg-zinc-800', description: "The flagship model in the 323 multi-function line, boasting an Auto Document Feeder for extreme productivity.", details: "The ultimate enterprise edge-device, permitting ultra-fast scanning of large document stacks alongside rapid printing.", specifications: [{label: 'Output Speed', value: '30 ppm'}, {label: 'Hardware', value: 'Integrated ADF'}, {label: 'Connectivity', value: 'Ethernet, Wi-Fi, USB'}], features: ['Print, Copy, Scan, ADF functionality', 'Automatic two-sided printing', 'Mobile printing support (AirPrint/Mopria)'] },
  { id: 'hp_126a', name: 'HP LaserJet Pro 126a', type: 'LASER', price: 23999, brand: 'HP', rating: 4.5, imageIcon: Monitor, badge: null, badgeColor: '', description: "A space-saving multi-function monochrome laser printer operating on a legendary toner platform.", details: "Relies on the globally recognized and highly available 88A toner cartridge, ensuring minimal downtime for supplies.", specifications: [{label: 'Print Speed', value: '21 ppm'}, {label: 'Resolution', value: '600x600 dpi'}, {label: 'Duty Cycle', value: '8000-page monthly duty cycle'}], features: ['High-quality flatbed scanner', 'Instant-on fuser technology', 'Dual-digit numeric LED panel'] },
  { id: 'hp_126nw', name: 'HP LaserJet Pro 126nw', type: 'LASER', price: 20499, brand: 'HP', rating: 4.6, imageIcon: Monitor, badge: null, badgeColor: '', description: "The wireless counterpart to the compact M126 laser architecture.", details: "Features wireless direct printing capabilities, allowing users to bypass localized router infrastructure entirely.", specifications: [{label: 'Print Speed', value: '21 ppm'}, {label: 'Connectivity', value: 'Built-in Ethernet, Wi-Fi, and USB'}], features: ['Wi-Fi Direct functionality', 'HP Smart app compatibility', 'Built upon the reliable 88A platform'] },
  { id: 'hp_p1108', name: 'HP LaserJet Pro P1108 plus', type: 'LASER', price: 15000, brand: 'HP', rating: 4.4, imageIcon: Printer, badge: null, badgeColor: '', description: "An ultra-compact, highly specialized single-function monochrome laser printer.", details: "Precision-engineered for tight desktop environments requiring exceptionally sharp, archival-quality black text.", specifications: [{label: 'Print Speeds', value: 'Up to 19 ppm'}, {label: 'Connectivity', value: 'USB interface'}], features: ['Energy-efficient internal architecture', 'Instant-on technology', 'Designed for individual workspace deployment'] },
  
  // --- INK ---
  { id: 'can_73_bk', name: 'Canon 73 (BK)', type: 'INK', price: 623, brand: 'Canon', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Specialized photographic black dye ink formulated exclusively for the G570/G670 series printers.", details: "Delivers incredibly dense shadows and striking contrast for glossy photo prints without pooling.", specifications: [{label: 'Capacity', value: '70ml'}], features: ['Spill-free keyed nozzle design', 'Produces a uniformly smooth gloss finish'] },
  { id: 'can_73_gy', name: 'Canon 73 (GY)', type: 'INK', price: 890, brand: 'Canon', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "A unique neutralizing grey dye ink for Canon's 6-color system.", details: "Crucial for expanding the tonal range in black-and-white photography and eliminating unwanted color casts.", specifications: [{label: 'Yield', value: '8000-page composite yield'}], features: ['Spill-free refill mechanism', 'Highly specialized for monochromatic stabilization'] },
  { id: 'can_73_r', name: 'Canon 73 (R)', type: 'INK', price: 890, brand: 'Canon', rating: 4.9, imageIcon: Droplet, badge: null, badgeColor: '', description: "A gamut-expanding vibrant red dye ink.", details: "Dramatically enhances warm tones, perfectly capturing the vividness of autumn landscapes and skin tones.", specifications: [{label: 'Yield', value: '8000-page composite yield'}], features: ['Precision, mess-free filling nozzle'] },
  { id: 'can_73_c', name: 'Canon 73 (C)', type: 'INK', price: 623, brand: 'Canon', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-vibrancy cyan dye ink for advanced photo reproduction.", details: "The foundational subtractive color essential for rendering flawless skies and the blue spectrum in the G-series.", specifications: [{label: 'Yield', value: '8000-page composite yield'}], features: ['Ensures perfectly consistent microscopic droplet formation'] },
  { id: 'can_73_y', name: 'Canon 73 (Y)', type: 'INK', price: 890, brand: 'Canon', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-vibrancy yellow dye ink for advanced photo reproduction.", details: "Acts as the primary colorant that injects underlying luminosity into complex printed mixtures.", specifications: [{label: 'Yield', value: '8000-page composite yield'}], features: ['Packaged in a specialized spill-resistant bottle'] },
  { id: 'can_73_m', name: 'Canon 73 (M)', type: 'INK', price: 890, brand: 'Canon', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-vibrancy magenta dye ink for advanced photo reproduction.", details: "The core subtractive primary responsible for generating deep purples and rich reds when blended.", specifications: [{label: 'Yield', value: '8000-page composite yield'}], features: ['Formulated with advanced anti-clogging chemistry'] },
  { id: 'can_71_pgbk', name: 'Canon 71 (PGBK)', type: 'INK', price: 484, brand: 'Canon', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "Standard heavy-duty pigment black ink designed for the general MegaTank lineup.", details: "Utilizes pigment particles to ensure printed text is exceptionally sharp, water-resistant, and highlighter-proof.", specifications: [{label: 'Yield', value: '3100 to 6000 pages depending on bottle'}], features: ['True pigment formulation', 'Equipped with a specialized bottle tip'] },
  { id: 'can_71_c', name: 'Canon 71 (C)', type: 'INK', price: 442, brand: 'Canon', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "Standard dye-based cyan ink for general office graphical needs.", details: "Delivers smooth color fills for standard charts, graphs, and basic document images.", specifications: [{label: 'Yield', value: '4400-page yield'}], features: ['Stable dye-based chemistry ensuring a long shelf life'] },
  { id: 'can_71_m', name: 'Canon 71 (M)', type: 'INK', price: 442, brand: 'Canon', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "Standard dye-based magenta ink for general office graphical needs.", details: "Blends seamlessly with yellow and cyan to accurately replicate standard business color palettes.", specifications: [{label: 'Yield', value: '4400-page yield'}], features: ['Dye-based with highly consistent flow dynamics'] },
  { id: 'can_71_y', name: 'Canon 71 (Y)', type: 'INK', price: 442, brand: 'Canon', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "Standard dye-based yellow ink for general office graphical needs.", details: "Chemically formulated to resist fading under standard indoor office lighting conditions.", specifications: [{label: 'Yield', value: '4400 to 7700 pages'}], features: ['Reliable dye-based formula'] },
  { id: 'can_70_pgbk', name: 'Canon 70 (PGBK)', type: 'INK', price: 875, brand: 'Canon', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy high-volume pigment black ink for older generation tank printers.", details: "Engineered strictly for intensive monochrome document creation where archival stability is paramount.", specifications: [{label: 'Chemistry', value: 'Heavy-duty pigment chemistry'}], features: ['Renders text highly resistant to water droplets', 'Marker smearing resistant'] },
  { id: 'can_70_y', name: 'Canon 70 (Y)', type: 'INK', price: 800, brand: 'Canon', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-volume yellow dye ink for legacy MegaTank systems.", details: "Serves as a fundamental color component for older, heavy-use hardware infrastructures.", specifications: [{label: 'Capacity', value: 'High yield volumetric capacity'}], features: ['Employs a specialized fade-resistant dye'] },
  { id: 'can_70_c', name: 'Canon 70 (C)', type: 'INK', price: 449, brand: 'Canon', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-volume cyan dye ink for legacy MegaTank systems.", details: "Provides high-capacity fluid replenishment for decentralized offices dealing with graphic-heavy workloads.", specifications: [{label: 'Capacity', value: 'High yield volumetric capacity'}], features: ['Supports the rendering of exceptionally smooth color gradients'] },
  { id: 'can_70_m', name: 'Canon 70 (M)', type: 'INK', price: 800, brand: 'Canon', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-volume magenta dye ink for legacy MegaTank systems.", details: "A core colorant necessary for full-spectrum document generation in earlier models.", specifications: [{label: 'Capacity', value: 'High yield volumetric capacity'}], features: ['Maintains a highly consistent liquid viscosity'] },
  { id: 'can_790_bk', name: 'Canon 790 (BK)', type: 'INK', price: 595, brand: 'Canon', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "Foundational pigment black ink powering early entry-level MegaTank units.", details: "Designed to maximize economy per page without sacrificing the optical density of the printed text.", specifications: [{label: 'Yield', value: 'Rated for a 6000-page yield'}], features: ['Highly cost-effective', 'Delivering deep, rich black output'] },
  { id: 'can_790_y', name: 'Canon 790 (Y)', type: 'INK', price: 595, brand: 'Canon', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "Entry-level yellow dye ink for the G2000/G3000 series.", details: "Formulated to perfectly saturate standard copy paper without causing the paper to over-soak and curl.", specifications: [{label: 'Yield', value: 'Rated for a 7000-page composite yield'}], features: ['Utilizes a rapid quick-drying mechanism'] },
  { id: 'can_790_c', name: 'Canon 790 (C)', type: 'INK', price: 595, brand: 'Canon', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "Entry-level cyan dye ink for the G2000/G3000 series.", details: "Guarantees that business graphics retain their quality even on inexpensive plain paper.", specifications: [{label: 'Yield', value: 'Rated for a 7000-page composite yield'}], features: ['Contains specialized anti-coagulation chemicals to protect the printhead'] },
  { id: 'can_790_m', name: 'Canon 790 (M)', type: 'INK', price: 595, brand: 'Canon', rating: 4.7, imageIcon: Droplet, badge: 'Value Pack', badgeColor: 'bg-green-500', description: "Entry-level magenta dye ink for the G2000/G3000 series.", details: "Completes the basic CMYK color space required for everyday home and small office printing.", specifications: [{label: 'Yield', value: 'Rated for a 7000-page composite yield'}], features: ['Packaged in an easy-pour, user-friendly bottle'] },
  { id: 'eps_l8050_bk', name: 'Epson L8050 ink (BK)', type: 'INK', price: 500, brand: 'Epson', rating: 4.9, imageIcon: Droplet, badge: 'Pro Photo', badgeColor: 'bg-purple-500', description: "A premium photographic dye-based black ink designed exclusively for Epson's advanced 6-color system.", details: "Specifically formulated to rest on the surface of glossy photo paper rather than soaking through, ensuring sharp contrast.", specifications: [{label: 'Capacity', value: '70ml bottle capacity'}], features: ['Dye-based to maintain perfect gloss compatibility', 'Delivering immense black density'] },
  { id: 'eps_l8050_c', name: 'Epson L8050 ink (C)', type: 'INK', price: 500, brand: 'Epson', rating: 4.9, imageIcon: Droplet, badge: null, badgeColor: '', description: "Photographic cyan dye ink for the L8050 series.", details: "Acts as a foundational primary color for generating vivid, true-to-life photographic blues.", specifications: [{label: 'Capacity', value: '70ml bottle capacity'}], features: ['Exceptional vivid hue rendering capabilities'] },
  { id: 'eps_l8050_y', name: 'Epson L8050 ink (Y)', type: 'INK', price: 500, brand: 'Epson', rating: 4.9, imageIcon: Droplet, badge: null, badgeColor: '', description: "Photographic yellow dye ink for the L8050 series.", details: "Provides brilliant luminosity and warmth to complex photo prints.", specifications: [{label: 'Capacity', value: '70ml bottle capacity'}], features: ['Features a strong UV-resistant chemical profile'] },
  { id: 'eps_l8050_m', name: 'Epson L8050 ink (M)', type: 'INK', price: 500, brand: 'Epson', rating: 4.9, imageIcon: Droplet, badge: null, badgeColor: '', description: "Photographic magenta dye ink for the L8050 series.", details: "A core primary colorant that mixes smoothly with other dyes for perfect color synthesis.", specifications: [{label: 'Capacity', value: '70ml bottle capacity'}], features: ['Exceptional smooth mixing and blending properties'] },
  { id: 'eps_l8050_lc', name: 'Epson L8050 ink (LC)', type: 'INK', price: 500, brand: 'Epson', rating: 4.9, imageIcon: Droplet, badge: null, badgeColor: '', description: "Highly specialized Light Cyan dye ink for 6-color systems.", details: "Diluted cyan that allows the printer to render soft blue skies and water textures without utilizing harsh, visible dots.", specifications: [{label: 'Capacity', value: '70ml bottle capacity'}], features: ['Drastically reduces the visibility of halftone dithering patterns in light areas'] },
  { id: 'eps_l8050_lm', name: 'Epson L8050 ink (LM)', type: 'INK', price: 500, brand: 'Epson', rating: 4.9, imageIcon: Droplet, badge: null, badgeColor: '', description: "Highly specialized Light Magenta dye ink for 6-color systems.", details: "A diluted magenta crucial for accurately reproducing natural, smooth human skin tones in portraiture.", specifications: [{label: 'Capacity', value: '70ml bottle capacity'}], features: ['Enables completely seamless tonal transitions in highlights and midtones'] },
  { id: 'eps_l8180_g', name: 'Epson L8180 (G)', type: 'INK', price: 800, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Neutralizing grey ink developed for the high-end Claria ET Premium system.", details: "Eradicates metamerism and guarantees perfect, tint-free black-and-white photographic reproduction.", specifications: [{label: 'Capacity', value: 'High-capacity bottle'}], features: ['Superbly stabilizes shadows in monochrome output'] },
  { id: 'eps_l8180_y', name: 'Epson L8180 (Y)', type: 'INK', price: 800, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Archival-quality yellow ink designed for A3+ large-format photo printing.", details: "Built to meet the exacting standards of professional photography requiring large, high-fidelity prints.", specifications: [{label: 'Capacity', value: 'High-capacity bottle'}], features: ['Delivers a premium high-gloss color finish'] },
  { id: 'eps_l8180_m', name: 'Epson L8180 (M)', type: 'INK', price: 800, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Archival-quality magenta ink designed for A3+ large-format photo printing.", details: "An essential component for the wide-gamut requirements of A3+ studio printing.", specifications: [{label: 'Capacity', value: 'High-capacity bottle'}], features: ['Delivers a premium high-gloss color finish'] },
  { id: 'eps_l8180_c', name: 'Epson L8180 (C)', type: 'INK', price: 800, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Archival-quality cyan ink designed for A3+ large-format photo printing.", details: "Provides vibrant sky and water reproduction on large-scale media.", specifications: [{label: 'Capacity', value: 'High-capacity bottle'}], features: ['Delivers a premium high-gloss color finish'] },
  { id: 'eps_l8180_bk', name: 'Epson L8180 (BK)', type: 'INK', price: 800, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Versatile photographic and document black ink for A3+ systems.", details: "An intelligent formulation that adapts its properties depending on the selected media, balancing gloss and durability.", specifications: [{label: 'Capacity', value: 'High-capacity bottle'}], features: ['Capable of producing water-resistant text as well as rich, glossy photo blacks'] },
  { id: 'eps_008_bk', name: 'Epson 008 (BK)', type: 'INK', price: 390, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: 'Enterprise', badgeColor: 'bg-zinc-800', description: "A highly resilient enterprise-grade pigment black ink.", details: "Powers heavy-duty printers like the L15150 series, providing crispness that directly rivals laser toners.", specifications: [{label: 'Capacity', value: '127ml bottle capacity'}, {label: 'Yield', value: '7500-page yield'}], features: ['True pigment formulation that dries instantly', 'Completely resistant to water and smudges'] },
  { id: 'eps_008_c', name: 'Epson 008 (C)', type: 'INK', price: 526, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-performance enterprise pigment cyan ink.", details: "Ensures that important business graphics and logos survive environmental exposure and handling.", specifications: [{label: 'Capacity', value: '100ml packaging variant'}], features: ['Highly fade-resistant', 'Delivering incredibly crisp graphic edges'] },
  { id: 'eps_008_y', name: 'Epson 008 (Y)', type: 'INK', price: 526, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-performance enterprise pigment yellow ink.", details: "Formulated to prevent bleeding or yellowing over time, even on standard, low-cost copy paper.", specifications: [{label: 'Capacity', value: '100ml packaging variant'}], features: ['Boasts extreme pigment-based durability'] },
  { id: 'eps_008_m', name: 'Epson 008 (M)', type: 'INK', price: 526, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-performance enterprise pigment magenta ink.", details: "Offers high opacity, making it perfect for rendering distinct, readable business charts and graphs.", specifications: [{label: 'Capacity', value: '100ml packaging variant'}], features: ['Exceptionally smudge-resistant formulation'] },
  { id: 'eps_005_bk', name: 'Epson 005 (BK)', type: 'INK', price: 200, brand: 'Epson', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy monochrome pigment ink designed for early heavy-duty EcoTank models.", details: "Created as a direct, high-volume liquid alternative to traditional laser printer toners.", specifications: [{label: 'Capacity', value: '120ml bottle volume'}], features: ['Extremely high-yield', 'Cost-effective formulation'] },
  { id: 'eps_003_c', name: 'Epson 003 (C)', type: 'INK', price: 265, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: 'Bestseller', badgeColor: 'bg-green-500', description: "The ubiquitous entry-level cyan dye ink powering millions of home office printers.", details: "The fluid responsible for the incredible cost-efficiency of Epson's massive L-series install base.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Features anti-coagulating properties', 'Produces bright color output'] },
  { id: 'eps_003_m', name: 'Epson 003 (M)', type: 'INK', price: 265, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "The ubiquitous entry-level magenta dye ink.", details: "A standard primary colorant relied upon heavily for basic home office graphics and school projects.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Incorporates a uniquely easy, mess-free refill design'] },
  { id: 'eps_003_y', name: 'Epson 003 (Y)', type: 'INK', price: 265, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "The ubiquitous entry-level yellow dye ink.", details: "A standard primary colorant relied upon heavily for basic home office graphics.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Delivers surprisingly vibrant saturation for an entry-level dye'] },
  { id: 'eps_003_bk', name: 'Epson 003 (BK)', type: 'INK', price: 404, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "The core entry-level dye-based black ink for standard EcoTank models.", details: "The primary text-generating fluid for popular models like the L3110 and L3250 used globally.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Produces a rich dye black via a completely mess-free refill mechanism'] },
  { id: 'eps_001_c', name: 'Epson 001 (C)', type: 'INK', price: 500, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "An intermediate cyan ink designed for mid-tier enterprise hardware.", details: "Perfectly bridges the operational gap between light home use and heavy corporate usage.", specifications: [{label: 'Yield', value: 'High page yield capacity'}], features: ['Utilizes Epson\'s auto-stop refill technology to prevent spills'] },
  { id: 'eps_001_m', name: 'Epson 001 (M)', type: 'INK', price: 500, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "An intermediate magenta ink designed for mid-tier enterprise hardware.", details: "The standard magenta component necessary for reliable mid-tier color output.", specifications: [{label: 'Yield', value: 'High page yield capacity'}], features: ['Engineered for exceptionally smooth fluid flow dynamics'] },
  { id: 'eps_001_y', name: 'Epson 001 (Y)', type: 'INK', price: 500, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "An intermediate yellow ink designed for mid-tier enterprise hardware.", details: "The standard yellow component necessary for reliable mid-tier color output.", specifications: [{label: 'Yield', value: 'High page yield capacity'}], features: ['Chemically UV-stabilized to prevent premature fading'] },
  { id: 'eps_001_bk', name: 'Epson 001 (BK)', type: 'INK', price: 500, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "An intermediate black ink designed for high-volume invoice and contract generation.", details: "Ensures that dense, readable black text is produced consistently during long print runs.", specifications: [{label: 'Yield', value: 'High page yield capacity'}], features: ['Imbued with water-resistant properties to protect vital documents'] },
  { id: 'eps_673_c', name: 'Epson 673 (C)', type: 'INK', price: 320, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy primary cyan dye ink for older 6-color photo systems like the L805.", details: "Lays the vital chromatic framework needed for producing beautiful, archival-quality photographs.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Tailored specifically to bond perfectly with glossy photographic media'] },
  { id: 'eps_673_m', name: 'Epson 673 (M)', type: 'INK', price: 320, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy primary magenta dye ink for older 6-color photo systems.", details: "Lays the vital chromatic framework needed for producing beautiful, archival-quality photographs.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Tailored specifically to bond perfectly with glossy photographic media'] },
  { id: 'eps_673_y', name: 'Epson 673 (Y)', type: 'INK', price: 320, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy primary yellow dye ink for older 6-color photo systems.", details: "Lays the vital chromatic framework needed for producing beautiful, archival-quality photographs.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Tailored specifically to bond perfectly with glossy photographic media'] },
  { id: 'eps_673_bk', name: 'Epson 673 (BK)', type: 'INK', price: 320, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy black dye ink formulated for renowned photo printers like the L1800.", details: "Specially designed to render deep, stunning contrast in photographic shadows and dark scenes.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Ensures rich black density on glossy surfaces'] },
  { id: 'eps_673_lc', name: 'Epson 673 (LC)', type: 'INK', price: 320, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy Light Cyan mid-tone dye ink.", details: "An absolutely crucial element enabling the L1800 to print massive, grain-free images of skies and water.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Provides unmatched gradient control and tonal smoothness'] },
  { id: 'eps_673_lm', name: 'Epson 673 (LM)', type: 'INK', price: 320, brand: 'Epson', rating: 4.8, imageIcon: Droplet, badge: null, badgeColor: '', description: "Legacy Light Magenta mid-tone dye ink.", details: "An absolutely crucial element for delicately rendering accurate, flawless skin tones in large-format portraits.", specifications: [{label: 'Capacity', value: '65 ml bottle volume'}], features: ['Facilitates completely seamless tonal blending'] },
  { id: 'eps_664_bk', name: 'Epson 664 (BK)', type: 'INK', price: 404, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "The foundational black ink that powered early-generation 4-color L-series models.", details: "The reliable fluid behind legacy workhorses like the L130, L210, and L380.", specifications: [{label: 'Capacity', value: '70 ml bottle volume'}, {label: 'Yield', value: '4500 to 6000 pages'}], features: ['A dye-based formula meticulously designed to extend the lifespan of the internal piezo head'] },
  { id: 'eps_664_y', name: 'Epson 664 (Y)', type: 'INK', price: 450, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "Foundational yellow dye ink for early-generation general-purpose printing.", details: "An extremely stable fluid designed to provide consistent color over years of operation.", specifications: [{label: 'Capacity', value: '70 ml bottle volume'}], features: ['Highly reliable formulation with an excellent page yield'] },
  { id: 'eps_664_c', name: 'Epson 664 (C)', type: 'INK', price: 450, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "Foundational cyan dye ink for early-generation general-purpose printing.", details: "An extremely stable fluid designed to provide consistent color over years of operation.", specifications: [{label: 'Capacity', value: '70 ml bottle volume'}], features: ['Highly reliable formulation with an excellent page yield'] },
  { id: 'eps_664_m', name: 'Epson 664 (M)', type: 'INK', price: 450, brand: 'Epson', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "Foundational magenta dye ink for early-generation general-purpose printing.", details: "An extremely stable fluid designed to provide consistent color over years of operation.", specifications: [{label: 'Capacity', value: '70 ml bottle volume'}], features: ['Highly reliable formulation with an excellent page yield'] },
  { id: 'eps_774_bk', name: 'Epson 774 (BK)', type: 'INK', price: 350, brand: 'Epson', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "Ultra-high-capacity monochrome pigment ink designed for specific M-series printers.", details: "Formulated exclusively for high-volume mono units like the M100 and M200, serving as a direct laser replacement.", specifications: [{label: 'Capacity', value: 'Large 100ml to 140ml capacities'}], features: ['A true pigment base delivering completely water-resistant, laser-sharp text reproduction'] },
  { id: 'hp_gt52_c', name: 'HP GT52 (C)', type: 'INK', price: 500, brand: 'HP', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "Vibrant cyan thermal dye ink engineered for the HP Smart Tank series.", details: "Scientifically formulated to vaporize instantaneously, forming perfectly spherical micro-droplets without clogging the thermal head.", specifications: [{label: 'Yield', value: 'Contributes to a composite yield of up to 8000 color pages'}], features: ['Features an advanced anti-clogging and fade-resistant chemical profile'] },
  { id: 'hp_gt52_m', name: 'HP GT52 (M)', type: 'INK', price: 500, brand: 'HP', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "Vibrant magenta thermal dye ink engineered for the HP Smart Tank series.", details: "The vital colorant required for flawlessly blending reds and purples in office charting and graphics.", specifications: [{label: 'Yield', value: 'Contributes to a composite yield of up to 8000 color pages'}], features: ['Guarantees highly precise droplet formation during the thermal boiling process'] },
  { id: 'hp_gt52_y', name: 'HP GT52 (Y)', type: 'INK', price: 500, brand: 'HP', rating: 4.6, imageIcon: Droplet, badge: null, badgeColor: '', description: "Vibrant yellow thermal dye ink engineered for the HP Smart Tank series.", details: "Injects necessary luminosity and brightness into the printed CMYK mixture.", specifications: [{label: 'Yield', value: 'Contributes to a composite yield of up to 8000 color pages'}], features: ['Employs a rapid-drying chemical architecture to prevent smudging'] },
  { id: 'hp_gt53_bk', name: 'HP GT53 (BK)', type: 'INK', price: 500, brand: 'HP', rating: 4.7, imageIcon: Droplet, badge: null, badgeColor: '', description: "High-density black ink designed to withstand the extreme thermal cycles of HP printheads.", details: "Meticulously formulated to prevent carbonized crusting (kogation) on internal micro-resistors over millions of firings.", specifications: [{label: 'Yield', value: 'Extremely high volume page yield'}], features: ['Renders incredibly crisp text with deep optical density and sharp edge acuity'] },

  // --- MAINTENANCE & COMPONENTS ---
  { id: 'can_mcg01', name: 'Canon MC-G01 Maintenance Box', type: 'MAINTENANCE', price: 170, brand: 'Canon', rating: 4.5, imageIcon: Settings, badge: null, badgeColor: '', description: "A high-capacity waste ink receptacle designed for the robust MAXIFY series.", details: "Safely absorbs ink purged during automated deep-cleaning cycles, preventing catastrophic internal flooding of the chassis.", specifications: [{label: 'Capacity', value: 'Engineered for enterprise workloads'}], features: ['Completely user-replaceable', 'Embedded IC chip to precisely track remaining capacity'] },
  { id: 'can_mcg02', name: 'Canon MC-G02 Maintenance Cartridge', type: 'MAINTENANCE', price: 185, brand: 'Canon', rating: 4.5, imageIcon: Settings, badge: null, badgeColor: '', description: "The essential maintenance cartridge for mid-tier G-series and 6-color photo printers.", details: "Vitally important for photo printers (like the G570/G670) which frequently run micro-cleaning routines to keep nozzles moist.", specifications: [{label: 'Tracking', value: 'Includes an integrated capacity-tracking IC chip'}], features: ['Accessible via an easy-open panel', 'Preventing the dreaded Error 5BOO factory-lockout scenario'] },
  { id: 'can_mcg03', name: 'Canon MC-G03 Maintenance Box', type: 'MAINTENANCE', price: 2499, brand: 'Canon', rating: 4.7, imageIcon: Settings, badge: 'Heavy Duty', badgeColor: 'bg-zinc-800', description: "A heavy-duty maintenance box constructed for the GX3010 and 4030 MAXIFY platforms.", details: "Scaled to handle the massive waste-ink output of small-to-medium businesses churning through thousands of pages.", specifications: [{label: 'Material', value: 'Filled with high-density, rapidly absorbing industrial foam'}], features: ['Hot-swappable design', 'Proactive software alerts before the unit reaches maximum saturation'] },
  { id: 'can_mcg04', name: 'Canon MC-G04 Maintenance Box', type: 'MAINTENANCE', price: 130, brand: 'Canon', rating: 4.4, imageIcon: Settings, badge: null, badgeColor: '', description: "A structurally unique waste receptacle designed for compact units like the G2770 and G3770.", details: "Allows the printer to maintain a remarkably small desk footprint by perfectly utilizing internal cavity geometries to store waste fluid.", specifications: [{label: 'Weight', value: 'Packaged with a 0.50 kg volumetric weight'}], features: ['Simple snap-in installation', 'Manages printhead hygiene without expanding the device physical size'] },
  { id: 'can_mcg05', name: 'Canon MC-G05 Maintenance Box', type: 'MAINTENANCE', price: 250, brand: 'Canon', rating: 4.5, imageIcon: Settings, badge: null, badgeColor: '', description: "A compact, budget-friendly waste ink cartridge for entry-level devices.", details: "A highly affordable consumable that guarantees entry-level hardware can remain functional for years rather than becoming e-waste.", specifications: [{label: 'Material', value: 'Utilizes standard absorption materials'}], features: ['Fully user-serviceable', 'Indefinitely extending the printer operational lifecycle'] },
  { id: 'hp_moh51aa', name: 'HP MOH51AA Print Head (Black)', type: 'PRINT HEAD', price: 1150, brand: 'HP', rating: 4.6, imageIcon: Wrench, badge: null, badgeColor: '', description: "An Original Black GT Replacement Printhead for HP Ink Tank systems.", details: "Circumvents the inherent degradation of thermal printheads by allowing users to easily swap the burnt-out part for a fresh one.", specifications: [{label: 'Lifespan', value: 'Rated to deliver approximately 5000 pages of peak thermal firing performance'}], features: ['Simple drop-in mechanism that instantly restores factory-level print clarity', 'Eliminating all banding and streaking'] },
  { id: 'hp_moh50aa', name: 'HP MOH50AA Print Head (Tri-Color)', type: 'PRINT HEAD', price: 1150, brand: 'HP', rating: 4.6, imageIcon: Wrench, badge: null, badgeColor: '', description: "An Original Tri-Color GT Replacement Printhead for HP Ink Tank systems.", details: "Houses the intricate microscopic resistors necessary to successfully fire the Cyan, Magenta, and Yellow GT52 inks.", specifications: [{label: 'Design', value: 'Features an integrated, highly precise tri-color nozzle plate'}], features: ['Factory-calibrated for flawless color alignment', 'Can be trivially seated by the user without requiring specialized tools'] },

  // --- PERIPHERALS (MOUSE & KEYBOARD) ---
  { id: 'fin_masterhit', name: 'Fingers MasterHit', type: 'PERIPHERALS', price: 230, brand: 'Fingers', rating: 4.2, imageIcon: Mouse, badge: null, badgeColor: '', description: "A fundamentally reliable, utilitarian wired ambidextrous optical mouse.", details: "Purpose-built as a lightweight workhorse for high-volume enterprise deployments, educational labs, and basic data entry.", specifications: [{label: 'Resolution', value: '1200 DPI optical resolution'}, {label: 'Interface', value: 'USB 2.0 interface'}, {label: 'Lifespan', value: 'Switches rated for a 1 million actuation lifecycle'}], features: ['Standard Matte Black finish', '3-button layout with a scroll wheel', 'Offering true driverless plug-and-play simplicity'] },
  { id: 'fin_superhit', name: 'Fingers SuperHit (Multi Color)', type: 'PERIPHERALS', price: 249, brand: 'Fingers', rating: 4.3, imageIcon: Mouse, badge: null, badgeColor: '', description: "A highly reliable wired optical mouse offered in multiple expressive, dual-tone aesthetic finishes.", details: "Elevates standard utilitarian desk hardware by offering curated colorways that blend perfectly with modern interior room designs.", specifications: [{label: 'Sensor', value: 'Features an advanced optical sensor'}, {label: 'Interface', value: 'Wired USB connectivity'}], features: ['Available in eye-catching Graphite Grey, Sea Blue, Blush Pink, and Matte Black + Steel Grey', 'Features an ambidextrous shell'] },
  { id: 'fin_aerogripplus', name: 'Fingers AeroGrip plus', type: 'PERIPHERALS', price: 465, brand: 'Fingers', rating: 4.5, imageIcon: Mouse, badge: null, badgeColor: '', description: "A sophisticated 3-in-1 rechargeable optical mouse featuring both Bluetooth and RF wireless capabilities.", details: "Champions the transition to untethered workflows while eliminating the environmental and financial cost of disposable alkaline batteries.", specifications: [{label: 'Connectivity', value: 'Communicates via a 2.4GHz USB Receiver or Bluetooth'}, {label: 'Power', value: 'Internal rechargeable cell'}], features: ['Showcases premium Ash Brown and White aesthetics', 'Ergonomically contoured for palm and claw grips', 'Rapid multi-device switching'] },
  { id: 'fin_cherrygrip', name: 'Fingers CherryGrip', type: 'PERIPHERALS', price: 600, brand: 'Fingers', rating: 4.7, imageIcon: Mouse, badge: null, badgeColor: '', description: "A flagship 3-in-1 wireless optical mouse offering on-the-fly variable DPI and modern Type-C fast charging.", details: "Specifically engineered for power users who demand extreme mobility and pixel-perfect cursor control across multiple operating systems.", specifications: [{label: 'Connectivity', value: 'Dual Bluetooth v5.2 and 2.4 GHz modes'}, {label: 'Sensor', value: 'Variable 800-1200-1600 DPI sensor'}, {label: 'Battery', value: 'Robust 500 mAh internal battery'}], features: ['Striking Cherry Red colorway', '5 tactile input buttons', 'Type-C charging (yielding up to 25 days backup)', 'Seamless OS hopping (macOS, Windows, iPadOS, Android)'] },
  { id: 'fin_rangeela', name: 'Fingers Rangeela (Multi Color)', type: 'PERIPHERALS', price: 875, brand: 'Fingers', rating: 4.6, imageIcon: Keyboard, badge: null, badgeColor: '', description: "A visually striking, multi-device deskset available in wired and wireless variations, defined by its vivid color schemes.", details: "Deliberately shatters the boring monochromatic norms of office gear, injecting vivid personality into the workspace alongside practical spill-proof engineering.", specifications: [{label: 'Mouse', value: 'Includes a 1000 DPI mouse'}, {label: 'Connectivity', value: '2.4 GHz Wireless or standard Wired connections'}], features: ['Available in stunning Pearl Grey + Orange, Pearl Grey + White, Blue Shades, and Brown Shades', 'Includes soft-touch media controls and an Auto Power Save Mode'] },
  { id: 'fin_aeroclick', name: 'Fingers Aero Click Combo', type: 'PERIPHERALS', price: 1375, brand: 'Fingers', rating: 4.5, imageIcon: Keyboard, badge: null, badgeColor: '', description: "A sleek, minimalist wireless keyboard and mouse set prioritizing clean aesthetics and uninterrupted productivity.", details: "Designed to completely eradicate cable clutter from the desk while retaining a full-sized layout, complete with a numpad for accounting tasks.", specifications: [{label: 'Connectivity', value: 'Operates on a 2.4 GHz wireless frequency via a single, shared nano receiver'}], features: ['Offers seamless wireless deployment', 'Extended battery endurance', 'Satisfying tactile membrane keystrokes'] },
  { id: 'fin_teenyclicks', name: 'Fingers TeenyClicks', type: 'PERIPHERALS', price: 736, brand: 'Fingers', rating: 4.4, imageIcon: Keyboard, badge: null, badgeColor: '', description: "An ultra-compact, laptop-profile wireless keyboard capable of pairing with multiple devices simultaneously.", details: "Employs a tenkeyless (60%) layout by stripping away the numpad, which allows the mouse to be placed closer to the body, vastly improving shoulder ergonomics.", specifications: [{label: 'Dimensions', value: '285(L)x133(W)x18(H) mm, weighs merely 304g'}, {label: 'Battery', value: 'Offers up to 45 days of battery longevity'}], features: ['Finished in Jet Black', 'Includes dedicated multimedia keys', 'Facilitates instant multi-device switching', 'Perfected for space-constrained desks'] },
  { id: 'fin_btfreedom', name: 'Fingers BT-Freedom', type: 'PERIPHERALS', price: 470, brand: 'Fingers', rating: 4.5, imageIcon: Keyboard, badge: null, badgeColor: '', description: "An impossibly slim, highly portable Bluetooth mini keyboard utilizing premium X-Type scissor switches.", details: "Competes directly with the tactile feel of high-end laptops; crafted for the nomadic professional working from coffee shops or heavily utilizing tablets.", specifications: [{label: 'Layout', value: '78-key layout, switches rated for 10 million actuations'}, {label: 'Power', value: 'Powered by a 150 mAh rechargeable cell'}], features: ['Jet Black finish', 'Modern Type-C charging (providing up to 30 days of backup)', 'Connects to 3 devices simultaneously', 'Features a whisper-soft typing profile'] },
  { id: 'fin_chessycombo', name: 'Fingers ChessyCombo', type: 'PERIPHERALS', price: 825, brand: 'Fingers', rating: 4.3, imageIcon: Keyboard, badge: null, badgeColor: '', description: "A highly durable, budget-conscious wired keyboard and mouse set designed for massive enterprise value.", details: "Strips away unnecessary frills to focus purely on longevity, precise cursor control, and reliable tactile input for bulk corporate purchasing.", specifications: [{label: 'Connectivity', value: 'Standard wired USB interfaces for both the keyboard and the optical mouse sensor'}], features: ['Offers true plug-and-play softwareless deployment', 'Boasts a highly resilient membrane construction'] },
  { id: 'antesports_km540', name: 'AntEsports KM540', type: 'PERIPHERALS', price: 949, brand: 'AntEsports', rating: 4.8, imageIcon: Keyboard, badge: 'Gamer Choice', badgeColor: 'bg-red-600', description: "A competitive, gaming-oriented backlit membrane keyboard paired with a precision programmable mouse.", details: "Acts as the perfect bridge between standard office typing and competitive PC gaming, bringing aggressive visual flair and deep macro customization to the desk.", specifications: [{label: 'Mouse', value: 'Wired USB connection, Mouse boasts variable DPI (800/1600/2400/3200)'}, {label: 'Keyboard', value: 'Keyboard switches rated for a massive 50 million keystroke lifecycle'}], features: ['Features 7 distinct Rainbow backlit modes', 'An ergonomic wrist rest', 'A rigid brushed metal top plate', 'Durable braided 1.5m cables', 'Anti-slip rubber feet'] },

  // --- ACCESSORIES (CABLES, STORAGE, ETC) ---
  { id: 'ranz_15m_usb', name: 'Ranz 1.5m USB Printer Cable', type: 'ACCESSORIES', price: 150, brand: 'Ranz', rating: 4.4, imageIcon: Link, badge: null, badgeColor: '', description: "A foundational, heavy-duty USB Type-A to Type-B peripheral connection cable.", details: "Guarantees zero-latency, rock-solid data transmission between a standard desktop computer and an adjacent printer.", specifications: [{label: 'Length', value: '1.5-meter length'}, {label: 'Protocol', value: 'Utilizes standard USB data transmission protocols'}], features: ['Heavily shielded to block detrimental electromagnetic interference generated by nearby power cords'] },
  { id: 'ranz_3m_usb', name: 'Ranz 3m USB Printer Cable', type: 'ACCESSORIES', price: 250, brand: 'Ranz', rating: 4.5, imageIcon: Link, badge: null, badgeColor: '', description: "An extended-length USB Type-A to Type-B connection cable.", details: "Provides the necessary slack for flexible office arrangements where the host PC cannot be situated immediately next to the printer.", specifications: [{label: 'Length', value: '3-meter physical length'}], features: ['Employs high-gauge internal copper wiring to actively prevent signal degradation over the extended distance'] },
  { id: 'ranz_5m_usb', name: 'Ranz 5m USB Printer Cable', type: 'ACCESSORIES', price: 350, brand: 'Ranz', rating: 4.5, imageIcon: Link, badge: null, badgeColor: '', description: "A maximum-length standard USB Type-A to Type-B routing cable.", details: "Pushes the absolute boundaries of the passive USB 2.0 length specification, perfect for complex, large-room office routing.", specifications: [{label: 'Length', value: '5-meter physical length'}], features: ['Wrapped in heavy-duty shielding', 'Features incredibly robust plastic connector housings'] },
  { id: 'ranz_power_15m', name: 'Ranz 2 PIN Power Cord (1.5m)', type: 'ACCESSORIES', price: 150, brand: 'Ranz', rating: 4.4, imageIcon: Zap, badge: null, badgeColor: '', description: "A universally standardized AC power delivery cord for various IT hardware.", details: "Serves as a fundamental infrastructure replacement component, commonly utilized for printer power bricks, monitor adapters, and laptop chargers.", specifications: [{label: 'Length', value: '1.5-meter length'}, {label: 'Specs', value: 'Rated for standard AC power transmission, utilizes the ubiquitous figure-8 interface'}], features: ['Sheathed in highly durable, heat-resistant PVC jacketing'] },
  { id: 'ranz_cat6_3m', name: 'Ranz CAT 6 Patch Cord (3m)', type: 'ACCESSORIES', price: 200, brand: 'Ranz', rating: 4.6, imageIcon: Link, badge: null, badgeColor: '', description: "A high-bandwidth twisted-pair network cable designed for rigid LAN deployment.", details: "An essential infrastructural component for hardwiring robust network printers or bridging remote workstations to a localized network switch.", specifications: [{label: 'Length', value: '3-meter length'}, {label: 'Certification', value: 'Certified to the CAT 6 standard'}], features: ['Fully supports Gigabit and 10 Gbps data speeds', 'Equipped with molded strain relief to prevent physical damage at the connector'] },
  { id: 'ranz_cat6_15m', name: 'Ranz CAT 6 Patch Cord (1.5m)', type: 'ACCESSORIES', price: 149, brand: 'Ranz', rating: 4.6, imageIcon: Link, badge: null, badgeColor: '', description: "A standard-length, high-speed twisted-pair network cable.", details: "The ideal length for connecting a desktop PC directly to an adjacent wall-mounted RJ45 jack or patching rack-mounted enterprise servers.", specifications: [{label: 'Length', value: '1.5-meter length'}, {label: 'Certification', value: 'Certified to the CAT 6 standard'}], features: ['Engineered to support extremely high-frequency network bandwidths without packet loss'] },
  { id: 'ranz_cat6_1m', name: 'Ranz CAT 6 Patch Cord (1m)', type: 'ACCESSORIES', price: 100, brand: 'Ranz', rating: 4.5, imageIcon: Link, badge: null, badgeColor: '', description: "A highly compact short-run twisted-pair network cable.", details: "Utilized almost exclusively by IT professionals inside server closets and patch panels to minimize dangerous cable clutter.", specifications: [{label: 'Length', value: '1-meter length'}, {label: 'Certification', value: 'Certified to the CAT 6 standard'}], features: ['Features a snagless boot design to allow for easy routing through dense server racks'] },
  { id: 'ranz_screen_cleaner', name: 'Ranz Screen Cleaning Expert RZ-CK31', type: 'ACCESSORIES', price: 150, brand: 'Ranz', rating: 4.5, imageIcon: Droplet, badge: null, badgeColor: '', description: "A specialized liquid sanitation kit designed for delicate LCD panels and peripherals.", details: "Chemically formulated to safely dissolve caustic skin oils and dust from sensitive printer touchscreens and monitors without stripping away vital anti-glare coatings.", specifications: [{label: 'Contents', value: 'Includes a bottle of anti-static cleaning fluid and a specialized microfiber cloth'}], features: ['Guarantees a completely non-abrasive, streak-free cleaning experience'] },
  { id: 'ranz_hdmi_4k', name: 'Ranz HDMI to HDMI Cable 4K2K 60Hz CABRIO', type: 'ACCESSORIES', price: 150, brand: 'Ranz', rating: 4.7, imageIcon: Link, badge: null, badgeColor: '', description: "An ultra-high-bandwidth digital video and audio transmission conduit.", details: "Capable of carrying massive streams of completely uncompressed high-definition data between modern PCs and digital projectors or monitors.", specifications: [{label: 'Specs', value: '1.5-meter length, boasts an 18.0 Gbps data bandwidth capacity'}], features: ['Flawlessly supports native 4K resolutions at a perfectly smooth 60Hz refresh rate'] },
  { id: 'ranz_vga_hdmi', name: 'Ranz VGA to HDMI Converter RZ-VGHDX', type: 'ACCESSORIES', price: 160, brand: 'Ranz', rating: 4.4, imageIcon: Link, badge: null, badgeColor: '', description: "An active hardware bridge that converts analog PC video outputs into modern digital HDMI signals.", details: "A critical IT savior device that allows older, legacy desktop towers (equipped only with VGA) to function seamlessly with modern HDMI-only boardroom televisions and monitors.", specifications: [{label: 'Hardware', value: 'Available in ABS plastic or Metal casing variants, features an internal digital-to-analog converter (DAC) microprocessor'}], features: ['Provides immediate plug-and-play active conversion', 'Select variants also feature integrated audio injection capabilities'] },
  { id: 'fin_fwf300', name: 'Fingers Wireless Dongle FWF300', type: 'ACCESSORIES', price: 645, brand: 'Fingers', rating: 4.6, imageIcon: Wifi, badge: null, badgeColor: '', description: "A high-velocity USB Wi-Fi network adapter for desktops and older laptops.", details: "Instantly modernizes older hardware or bypasses failed internal motherboards by providing a highly stable connection to 802.11n networks.", specifications: [{label: 'Specs', value: 'Speeds up to 300 Mbps, operates on the 2.4 GHz frequency, supports IEEE 802.11 b/g/n protocols'}], features: ['Houses a built-in antenna within a miniaturized frame (15x7x32 mm)', 'Boasts incredibly wide operating system support, including Linux architectures'] },
  { id: 'fin_fwf150', name: 'Fingers Wireless Dongle FWF150', type: 'ACCESSORIES', price: 444, brand: 'Fingers', rating: 4.5, imageIcon: Wifi, badge: null, badgeColor: '', description: "An ultra-compact, essential USB Wi-Fi network bridge.", details: "Provides a virtually invisible, highly unobtrusive networking solution for aging machines needing basic web access or localized wireless printing.", specifications: [{label: 'Specs', value: 'Speeds up to 150 Mbps, adheres to the standard IEEE 802.11 protocol'}], features: ['Offers a "just plug" immediate setup experience', "With an ultra-low physical profile that won't block adjacent USB ports"] },
  { id: 'smartpro_hdd', name: 'SmartPro 2.5" USB HDD CASE', type: 'ACCESSORIES', price: 125, brand: 'SmartPro', rating: 4.4, imageIcon: HardDrive, badge: null, badgeColor: '', description: "A protective external enclosure designed to house standard 2.5-inch SATA hard drives and Solid-State Drives.", details: "Empowers users to recycle and repurpose old mechanical laptop drives into highly portable, bus-powered external backup banks.", specifications: [{label: 'Specs', value: 'Available in USB 2.0 or USB 3.0 interface variants, featuring an internal SATA hardware bridge'}], features: ['Select models feature a shock-resistant outer chassis', 'True plug-and-play functionality', 'Require absolutely no bulky external power bricks'] },
  { id: 'lapcare_128', name: 'Lapcare SATA LPSSD128GB', type: 'ACCESSORIES', price: 970, brand: 'Lapcare', rating: 4.7, imageIcon: HardDrive, badge: 'Storage Upgrade', badgeColor: 'bg-blue-500', description: "A rapid, entry-level 128GB 2.5-inch SATA III internal Solid-State Drive.", details: "An aggressive, cost-effective storage upgrade designed purely to host the operating system, breathing entirely new life into sluggish, aging computers.", specifications: [{label: 'Specs', value: '128 GB total capacity, Read speeds peaking at 550MB/s, Write speeds up to 450MB/s'}], features: ['Highly shock-resistant', 'Serves as the ideal drop-in HDD replacement', 'Utilizes the SATA III 6Gbps standard'] },
  { id: 'lapcare_256', name: 'Lapcare SATA LPSSD256GB', type: 'ACCESSORIES', price: 1100, brand: 'Lapcare', rating: 4.8, imageIcon: HardDrive, badge: null, badgeColor: '', description: "An intermediate 256GB 2.5-inch SATA III internal Solid-State Drive.", details: "Offers the perfect balance, providing enough digital overhead for the operating system alongside daily productivity applications and their localized cache files.", specifications: [{label: 'Specs', value: 'Standard SATA interface with fast flash data transfer protocols'}], features: ['Backed by a 3-year warranty', 'Runs completely silently', 'Suffers from zero mechanical degradation over time'] },
  { id: 'lapcare_512', name: 'Lapcare SATA LPSSD512GB', type: 'ACCESSORIES', price: 1800, brand: 'Lapcare', rating: 4.8, imageIcon: HardDrive, badge: null, badgeColor: '', description: "A high-capacity 512GB 2.5-inch SATA III internal Solid-State Drive.", details: "Highly capable of acting as the solitary primary drive for a modern laptop, easily holding the OS, large applications, and significant localized media libraries.", specifications: [{label: 'Specs', value: 'Sequential Read speeds of 550MB/s, Write speeds of 450MB/s'}], features: ['Boasts extreme shock tolerance', 'Completely eliminates the latency associated with moving mechanical platters'] },
  { id: 'aarvex_128', name: 'AARVEX 128GB SATA AX950 pro Series SSD', type: 'ACCESSORIES', price: 950, brand: 'AARVEX', rating: 4.6, imageIcon: HardDrive, badge: 'Enterprise Storage', badgeColor: 'bg-zinc-800', description: "A highly reliable, compact 128GB SATA III solid-state drive.", details: "Purpose-built for rapid enterprise deployment in thin-clients and basic office workstations where massive localized file storage is completely unnecessary.", specifications: [{label: 'Specs', value: 'Built upon 3D TLC NAND Flash architecture, ultra-slim 100x70x7mm dimensions'}], features: ['Features native S.M.A.R.T tracking support', 'Deep TRIM command integration', 'Native Command Queuing (NCQ) optimization'] },
  { id: 'aarvex_256', name: 'AARVEX 256GB SATA AX950 pro Series SSD', type: 'ACCESSORIES', price: 1350, brand: 'AARVEX', rating: 4.7, imageIcon: HardDrive, badge: null, badgeColor: '', description: "An advanced intermediate 256GB SATA III solid-state drive.", details: "perfectly balances acquisition cost with a storage pool large enough to comfortably handle modern Windows environments and their continuous large update packages.", specifications: [{label: 'Specs', value: 'Utilizes the SATA III interface; controller architecture theoretically capable of reading up to 1950 MBPS internally'}], features: ['Driven by a high-quality SMI high-speed controller', 'Includes a robust 5-year warranty', 'Boasts an MTBF (Mean Time Between Failures) of 1000000 hours'] }
];

export const servicesList = [
  { 
    id: 'srv1', 
    title: 'PRINTER SERVICE', 
    desc: 'Expert repair and maintenance for all laser and inkjet printers. Fast turnaround.', 
    detailedOverview: 'Our specialized printer repair division is equipped to handle everything from standard paper feed issues to complex printhead replacements and network configuration errors. We service all major brands of laser, inkjet, and enterprise copiers using genuine OEM parts, ensuring your business experiences minimal downtime and returns to peak printing performance.',
    bullets: [
      'Complete printhead cleaning and replacement',
      'Paper jam resolution and roller maintenance',
      'Firmware updates and enterprise network configuration'
    ],
    icon: Printer, color: 'text-orange-500', bg: 'bg-orange-50' 
  },
  { 
    id: 'srv2', 
    title: 'CARTRIDGE SERVICE', 
    desc: 'Eco-friendly refilling, repairing of toner and ink cartridges.', 
    detailedOverview: 'We provide an eco-conscious and cost-effective alternative to buying new cartridges. Our advanced repairing process involves completely disassembling, cleaning, and refilling your empty toner and ink cartridges with premium-grade ink/toner. Each unit undergoes rigorous post-fill testing to guarantee crisp, factory-quality prints while significantly reducing your environmental footprint.',
    bullets: [
      'Premium-grade ink and toner powder refills',
      'Drum replacement and chip resetting',
      'Rigorous post-fill print quality testing'
    ],
    icon: Droplet, color: 'text-fuchsia-500', bg: 'bg-fuchsia-50' 
  },
  { 
    id: 'srv3', 
    title: 'LAPTOP & DESKTOP SERVICE', 
    desc: 'Comprehensive diagnostics, hardware repair, and software troubleshooting.', 
    detailedOverview: "From software issues to complex component-level repairs, our technicians provide end-to-end solutions for all your computing devices. Whether you're dealing with a failing hard drive, a cracked laptop screen, virus infections, or sluggish software performance, our fully equipped laboratory accurately diagnoses the root cause and implements precise, long-lasting fixes.",
    bullets: [
      'Motherboard and chip-level component repair',
      'Data recovery and storage upgrades (HDD to SSD)',
      'Virus removal, OS installation, and system optimization'
    ],
    icon: Monitor, color: 'text-cyan-500', bg: 'bg-cyan-50' 
  },
];

export const productImages = [
  'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&q=80&w=2000', // Modern Printer
  'https://images.unsplash.com/photo-1588600878108-578307a3cc9d?auto=format&fit=crop&q=80&w=2000', // Tech stack / Office gear
  'https://images.unsplash.com/photo-1541560052-5e137f229371?auto=format&fit=crop&q=80&w=2000', // Printed papers
  'https://images.unsplash.com/photo-1621360811029-792fce77140e?auto=format&fit=crop&q=80&w=2000'  // Office peripherals
];

export const serviceImages = [
  'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&q=80&w=2000', // Motherboard/Tech Repair
  'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=2000', // Technician working
  'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&q=80&w=2000', // Hardware components
  'https://images.unsplash.com/photo-1580828343064-fde4cad202d5?auto=format&fit=crop&q=80&w=2000'  // Electronics workspace
];

export const aboutImages = [
  'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=2000', // Premium corporate office
  'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=2000', // Team collaborating
  'https://images.unsplash.com/photo-1556761175-5973dc0f32d7?auto=format&fit=crop&q=80&w=2000', // Business discussion
  'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=2000'  // Corporate chart/growth
];

export const contactImages = [
  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=2000', // Tech support team working
  'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=2000', // Friendly professional smiling
  'https://images.unsplash.com/photo-1577563908411-50cb98976fea?auto=format&fit=crop&q=80&w=2000', // Clean workspace / communication
  'https://images.unsplash.com/photo-1596524430615-b46475ddff6e?auto=format&fit=crop&q=80&w=2000'  // Customer service concept
];

export const homeImages = [
  'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&q=80&w=2000', // Modern Printer
  'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=2000', // Tech lab / Motherboard
  'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=2000', // Circuit board
  'https://images.unsplash.com/photo-1541560052-5e137f229371?auto=format&fit=crop&q=80&w=2000'  // Printed papers
];

