const fs = require('fs');

const dbProducts = [
  {"id":"ranz_15m_usb_printer_cable","name":"1.5m USB Printer Cable"},
  {"id":"aarvex_128gb_sata_ax950_pro_series_ssd","name":"128GB SATA AX950 Pro Series SSD"},
  {"id":"ranz_2_pin_power_cord_15m","name":"2 PIN Power Cord (1.5m)"},
  {"id":"smartpro_25_usb_20_hdd_case","name":"2.5\" USB 2.0 HDD CASE"},
  {"id":"aarvex_256gb_nvme_ax950_pro_series_ssd","name":"256GB NVMe AX950 Pro Series SSD"},
  {"id":"aarvex_256gb_sata_ax950_pro_series_ssd","name":"256GB SATA AX950 Pro Series SSD"},
  {"id":"ranz_3m_usb_printer_cable","name":"3m USB Printer Cable"},
  {"id":"ranz_5m_usb_printer_cable","name":"5m USB Printer Cable"},
  {"id":"antesports_antesports_km540_gaming_keyboard_mouse_combo","name":"AntEsports KM540 Gaming Keyboard & Mouse Combo"},
  {"id":"canon_canon_gi70_c_cyan_ink_bottle","name":"Canon GI-70 C – Cyan Ink Bottle"},
  {"id":"canon_canon_gi70_m_magenta_ink_bottle","name":"Canon GI-70 M – Magenta Ink Bottle"},
  {"id":"canon_canon_gi70_pgbk_pigment_black_ink_bottle","name":"Canon GI-70 PGBK – Pigment Black Ink Bottle"},
  {"id":"canon_canon_gi70_y_yellow_ink_bottle","name":"Canon GI-70 Y – Yellow Ink Bottle"},
  {"id":"canon_canon_gi71_c_cyan_ink_bottle","name":"Canon GI-71 C – Cyan Ink Bottle"},
  {"id":"canon_canon_gi71_m_magenta_ink_bottle","name":"Canon GI-71 M – Magenta Ink Bottle"},
  {"id":"canon_canon_gi71_pgbk_pigment_black_ink_bottle","name":"Canon GI-71 PGBK – Pigment Black Ink Bottle"},
  {"id":"canon_canon_gi71_y_yellow_ink_bottle","name":"Canon GI-71 Y – Yellow Ink Bottle"},
  {"id":"canon_canon_gi73_bk_black_ink_bottle","name":"Canon GI-73 BK – Black Ink Bottle"},
  {"id":"canon_canon_gi73_c_cyan_ink_bottle","name":"Canon GI-73 C – Cyan Ink Bottle"},
  {"id":"canon_canon_gi73_gy_grey_ink_bottle","name":"Canon GI-73 GY – Grey Ink Bottle"},
  {"id":"canon_canon_gi73_m_magenta_ink_bottle","name":"Canon GI-73 M – Magenta Ink Bottle"},
  {"id":"canon_canon_gi73_r_red_ink_bottle","name":"Canon GI-73 R – Red Ink Bottle"},
  {"id":"canon_canon_gi73_y_yellow_ink_bottle","name":"Canon GI-73 Y – Yellow Ink Bottle"},
  {"id":"canon_canon_gi790_bk_black_ink_bottle","name":"Canon GI-790 BK – Black Ink Bottle"},
  {"id":"canon_canon_gi790_c_cyan_ink_bottle","name":"Canon GI-790 C – Cyan Ink Bottle"},
  {"id":"canon_canon_gi790_m_magenta_ink_bottle","name":"Canon GI-790 M – Magenta Ink Bottle"},
  {"id":"canon_canon_gi790_y_yellow_ink_bottle","name":"Canon GI-790 Y – Yellow Ink Bottle"},
  {"id":"canon_canon_maintenance_cartridge_mcg01","name":"Canon Maintenance Cartridge MC-G01"},
  {"id":"canon_canon_maintenance_cartridge_mcg02","name":"Canon Maintenance Cartridge MC-G02"},
  {"id":"canon_canon_maintenance_cartridge_mcg03","name":"Canon Maintenance Cartridge MC-G03"},
  {"id":"canon_canon_maintenance_cartridge_mcg04","name":"Canon Maintenance Cartridge MC-G04"},
  {"id":"canon_canon_maintenance_cartridge_mcg05","name":"Canon Maintenance Cartridge MC-G05"},
  {"id":"ranz_cat_6_patch_cord_15m","name":"CAT 6 Patch Cord (1.5m)"},
  {"id":"ranz_cat_6_patch_cord_1m","name":"CAT 6 Patch Cord (1m)"},
  {"id":"ranz_cat_6_patch_cord_3m","name":"CAT 6 Patch Cord (3m)"},
  {"id":"epson_ecotank_l8050","name":"EcoTank L8050"},
  {"id":"epson_epson_001_bk_black_ink_bottle","name":"Epson 001 BK – Black Ink Bottle"},
  {"id":"epson_epson_001_c_cyan_ink_bottle","name":"Epson 001 C – Cyan Ink Bottle"},
  {"id":"epson_epson_001_m_magenta_ink_bottle","name":"Epson 001 M – Magenta Ink Bottle"},
  {"id":"epson_epson_001_y_yellow_ink_bottle","name":"Epson 001 Y – Yellow Ink Bottle"},
  {"id":"epson_epson_003_bk_black_ink_bottle","name":"Epson 003 BK – Black Ink Bottle"},
  {"id":"epson_epson_003_c_cyan_ink_bottle","name":"Epson 003 C – Cyan Ink Bottle"},
  {"id":"epson_epson_003_m_magenta_ink_bottle","name":"Epson 003 M – Magenta Ink Bottle"},
  {"id":"epson_epson_003_y_yellow_ink_bottle","name":"Epson 003 Y – Yellow Ink Bottle"},
  {"id":"epson_epson_005_bk_black_ink_bottle","name":"Epson 005 BK – Black Ink Bottle"},
  {"id":"epson_epson_008_bk_black_ink_bottle","name":"Epson 008 BK – Black Ink Bottle"},
  {"id":"epson_epson_008_c_cyan_ink_bottle","name":"Epson 008 C – Cyan Ink Bottle"},
  {"id":"epson_epson_008_m_magenta_ink_bottle","name":"Epson 008 M – Magenta Ink Bottle"},
  {"id":"epson_epson_008_y_yellow_ink_bottle","name":"Epson 008 Y – Yellow Ink Bottle"},
  {"id":"epson_epson_012_bk_black_ink_bottle_l8180","name":"Epson 012 BK – Black Ink Bottle (L8180)"},
  {"id":"epson_epson_012_c_cyan_ink_bottle_l8180","name":"Epson 012 C – Cyan Ink Bottle (L8180)"},
  {"id":"epson_epson_012_g_grey_ink_bottle_l8180","name":"Epson 012 G – Grey Ink Bottle (L8180)"},
  {"id":"epson_epson_012_m_magenta_ink_bottle_l8180","name":"Epson 012 M – Magenta Ink Bottle (L8180)"},
  {"id":"epson_epson_012_y_yellow_ink_bottle_l8180","name":"Epson 012 Y – Yellow Ink Bottle (L8180)"},
  {"id":"epson_epson_057_bk_black_ink_bottle_l8050","name":"Epson 057 BK – Black Ink Bottle (L8050)"},
  {"id":"epson_epson_057_c_cyan_ink_bottle_l8050","name":"Epson 057 C – Cyan Ink Bottle (L8050)"},
  {"id":"epson_epson_057_lc_light_cyan_ink_bottle_l8050","name":"Epson 057 LC – Light Cyan Ink Bottle (L8050)"},
  {"id":"epson_epson_057_lm_light_magenta_ink_bottle_l8050","name":"Epson 057 LM – Light Magenta Ink Bottle (L8050)"},
  {"id":"epson_epson_057_m_magenta_ink_bottle_l8050","name":"Epson 057 M – Magenta Ink Bottle (L8050)"},
  {"id":"epson_epson_057_y_yellow_ink_bottle_l8050","name":"Epson 057 Y – Yellow Ink Bottle (L8050)"},
  {"id":"epson_epson_664_bk_black_ink_bottle","name":"Epson 664 BK – Black Ink Bottle"},
  {"id":"epson_epson_664_c_cyan_ink_bottle","name":"Epson 664 C – Cyan Ink Bottle"},
  {"id":"epson_epson_664_m_magenta_ink_bottle","name":"Epson 664 M – Magenta Ink Bottle"},
  {"id":"epson_epson_664_y_yellow_ink_bottle","name":"Epson 664 Y – Yellow Ink Bottle"},
  {"id":"epson_epson_673_bk_black_ink_bottle","name":"Epson 673 BK – Black Ink Bottle"},
  {"id":"epson_epson_673_c_cyan_ink_bottle","name":"Epson 673 C – Cyan Ink Bottle"},
  {"id":"epson_epson_673_lc_light_cyan_ink_bottle","name":"Epson 673 LC – Light Cyan Ink Bottle"},
  {"id":"epson_epson_673_lm_light_magenta_ink_bottle","name":"Epson 673 LM – Light Magenta Ink Bottle"},
  {"id":"epson_epson_673_m_magenta_ink_bottle","name":"Epson 673 M – Magenta Ink Bottle"},
  {"id":"epson_epson_673_y_yellow_ink_bottle","name":"Epson 673 Y – Yellow Ink Bottle"},
  {"id":"epson_epson_774_bk_black_ink_bottle","name":"Epson 774 BK – Black Ink Bottle"},
  {"id":"fingers_fingers_aeroclicks_combo_wireless_keyboard_mouse_set","name":"FINGERS AeroClicks Combo Wireless Keyboard & Mouse Set"},
  {"id":"fingers_fingers_aerogrip_plus_3in1_wireless_mouse","name":"FINGERS AeroGrip Plus 3-in-1 Wireless Mouse"},
  {"id":"fingers_fingers_btfreedom_mini_bluetooth_keyboard","name":"FINGERS BT-Freedom Mini Bluetooth Keyboard"},
  {"id":"fingers_fingers_cherrygrip_3in1_wireless_mouse","name":"FINGERS CherryGrip 3-in-1 Wireless Mouse"},
  {"id":"fingers_fingers_chessycombo_wired_keyboard_mouse_set","name":"FINGERS ChessyCombo Wired Keyboard & Mouse Set"},
  {"id":"fingers_fingers_masterhit_wired_mouse","name":"FINGERS MasterHit Wired Mouse"},
  {"id":"fingers_fingers_rangeela_series_keyboard_velvet_combo_c4","name":"FINGERS Rangeela Series Keyboard (Velvet Combo C4)"},
  {"id":"fingers_fingers_superhit_wired_mouse","name":"FINGERS SuperHit Wired Mouse"},
  {"id":"fingers_fingers_teenyclicks_mini_bluetooth_keyboard","name":"FINGERS TeenyClicks Mini Bluetooth Keyboard"},
  {"id":"ranz_hdmi_to_hdmi_cable_4k2k_60hz_cabrio","name":"HDMI to HDMI Cable 4K2K 60Hz CABRIO"},
  {"id":"hp_hp_gt52_c_cyan_ink_bottle","name":"HP GT52 C – Cyan Ink Bottle"},
  {"id":"hp_hp_gt52_m_magenta_ink_bottle","name":"HP GT52 M – Magenta Ink Bottle"},
  {"id":"hp_hp_gt52_y_yellow_ink_bottle","name":"HP GT52 Y – Yellow Ink Bottle"},
  {"id":"hp_hp_gt53_bk_black_ink_bottle","name":"HP GT53 BK – Black Ink Bottle"},
  {"id":"hp_hp_m0h50a_tricolor_replacement_gt_printhead_moh50aa","name":"HP M0H50A Tri-Color Replacement GT Printhead (MOH50AA)"},
  {"id":"hp_hp_m0h51a_black_replacement_gt_printhead_moh51aa","name":"HP M0H51A Black Replacement GT Printhead (MOH51AA)"},
  {"id":"hp_laser_303d","name":"Laser 303d"},
  {"id":"hp_laser_303dw","name":"Laser 303dw"},
  {"id":"hp_laser_mfp_323d","name":"Laser MFP 323d"},
  {"id":"hp_laser_mfp_323dnw","name":"Laser MFP 323dnw"},
  {"id":"hp_laser_mfp_323sdnw","name":"Laser MFP 323sdnw"},
  {"id":"hp_laserjet_pro_mfp_m126a","name":"LaserJet Pro MFP M126a"},
  {"id":"hp_laserjet_pro_mfp_m126nw","name":"LaserJet Pro MFP M126nw"},
  {"id":"hp_laserjet_pro_p1108_plus","name":"LaserJet Pro P1108 Plus"},
  {"id":"canon_pixma_g2010","name":"PIXMA G2010"},
  {"id":"canon_pixma_g2012","name":"PIXMA G2012"},
  {"id":"canon_pixma_g2770","name":"PIXMA G2770"},
  {"id":"canon_pixma_g3010","name":"PIXMA G3010"},
  {"id":"canon_pixma_g3012","name":"PIXMA G3012"},
  {"id":"canon_pixma_g3770","name":"PIXMA G3770"},
  {"id":"canon_pixma_g4010","name":"PIXMA G4010"},
  {"id":"canon_pixma_g570","name":"PIXMA G570"},
  {"id":"canon_pixma_g670","name":"PIXMA G670"},
  {"id":"lapcare_sata_lpssd128gb","name":"SATA LPSSD128GB"},
  {"id":"lapcare_sata_lpssd256gb","name":"SATA LPSSD256GB"},
  {"id":"lapcare_sata_lpssd512gb","name":"SATA LPSSD512GB"},
  {"id":"ranz_screen_cleaning_expert_rzck31","name":"Screen Cleaning Expert RZ-CK31"},
  {"id":"hp_smart_tank_525","name":"Smart Tank 525"},
  {"id":"hp_smart_tank_580","name":"Smart Tank 580"},
  {"id":"hp_smart_tank_585","name":"Smart Tank 585"},
  {"id":"ranz_vga_to_hdmi_converter_rzvghdx","name":"VGA to HDMI Converter RZ-VGHDX"},
  {"id":"fingers_wireless_dongle_fwf150","name":"Wireless Dongle FWF150"},
  {"id":"fingers_wireless_dongle_fwf300","name":"Wireless Dongle FWF300"}
];

const parsedFile = fs.readFileSync('parsed_products.js', 'utf8');

const missing = dbProducts.filter(p => !parsedFile.includes(p.id));

console.log(JSON.stringify(missing, null, 2));
